/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;



/**
 *
 * @author Mizan Saputro
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Menu Utama");
    }

    public JButton getBarang() {
        return barang;
    }

    public JButton getPemesanan() {
        return pemesanan;
    }
   
    public JButton getPembayaran() {
        return pembayaran;
    }
    
    public JButton getExit(){
        return exit;
    }
    public void addListener(ActionListener ae){
        barang.addActionListener(ae);
        pemesanan.addActionListener(ae);
        pembayaran.addActionListener(ae);
        exit.addActionListener(ae);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1_mainMenu = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        pembayaran = new javax.swing.JButton();
        pemesanan = new javax.swing.JButton();
        barang = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setTitle("Tubes PBO Pemesanan Barang");
        setFocusCycleRoot(false);

        jInternalFrame1_mainMenu.setVisible(true);

        jLabel1.setText("APLIKASI PEMESANAN BARANG");

        pembayaran.setText("Menu Pembayaran");
        pembayaran.setPreferredSize(new java.awt.Dimension(127, 23));
        pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranActionPerformed(evt);
            }
        });

        pemesanan.setText("Menu Pemesanan");
        pemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pemesananActionPerformed(evt);
            }
        });

        barang.setText("Menu Barang");
        barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangActionPerformed(evt);
            }
        });

        exit.setText("Keluar");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1_mainMenuLayout = new javax.swing.GroupLayout(jInternalFrame1_mainMenu.getContentPane());
        jInternalFrame1_mainMenu.getContentPane().setLayout(jInternalFrame1_mainMenuLayout);
        jInternalFrame1_mainMenuLayout.setHorizontalGroup(
            jInternalFrame1_mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1_mainMenuLayout.createSequentialGroup()
                .addGroup(jInternalFrame1_mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1_mainMenuLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(jInternalFrame1_mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barang, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame1_mainMenuLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1)))
                .addGap(0, 122, Short.MAX_VALUE))
        );
        jInternalFrame1_mainMenuLayout.setVerticalGroup(
            jInternalFrame1_mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1_mainMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(barang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pemesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(exit)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1_mainMenu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1_mainMenu, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pembayaranActionPerformed

    private void pemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pemesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pemesananActionPerformed

    private void barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barangActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barang;
    private javax.swing.JButton exit;
    private javax.swing.JInternalFrame jInternalFrame1_mainMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pembayaran;
    private javax.swing.JButton pemesanan;
    // End of variables declaration//GEN-END:variables
}
